[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
risk_oracle     = "u6LFtFvriSjCibNRsFBJgPi61m4LkDPLXM3HYndFMJX"
circuit_breaker = "9tQPx6NLzy81Lk3AQwA8EbnnCSPbrGezCmc58EkvDG8r"
rwa_vault       = "27LUs2phpTGbAQ5vkb1K44Aa45HW2JoViFat5st8keFE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
